services:
  showstart:
    build:
      context: ${SHOWSTART_CODE_PATH}
      dockerfile: ${SHOWSTART_DOCKERFILE_PATH}
      options:
        rm: true
    container_name: ${SHOWSTART_NAME}
    restart: always
    privileged: true
    image: ${SHOWSTART_NAME}:latest
    networks:
      - ${NETWORKS}
    ports:
      - 8000:8000
  front-showstart:
    build:
      context: ${FRONT_SHOWSTART_CODE_PATH}
      dockerfile: ${FRONT_SHOWSTART_DOCKERFILE_PATH}
      options:
        rm: true
    container_name: ${FRONT_SHOWSTART_NAME}
    restart: always
    privileged: true
    image: ${FRONT_SHOWSTART_NAME}:latest
    networks:
      - ${NETWORKS}
    ports:
      - 80:8100
    volumes:
      - ${FRONT_SHOWSTART_NGINX}:/etc/nginx"
networks:
  showstart:
    driver: bridge
