showstart:
  #从header里面获取该字段
  CUUSEREF:
  StFlpv:
  CUSUT:
  #用户信息
  ## 收货地址
  CustomerName: 收货姓名
  Province: 省份
  CityName: 城市
  Address: 详细地址
  Telephone:
  #如需观演人
  CommonPerformerID:
  #搜索演出关键字
  Keyword: 陈鸿宇
  #分页展示 页数
  Pagno: 1
  #演出相关信息
  ActivityId: 175865
  TicketId: f542fc4311e2cae04916efbf46111268
  #一个订单抢几张票 默认1张
  TicketNum: 1
  #指定多少毫米内随机抢票
  Ticker: 200
  #cron表达式 指定时间开始抢票
  #如果注释时间就是马上开抢
#  CronTime: 0 03 21 * * ?
  #订单数
  OrderNum: 1
logger:
  log_level: ERROR
server:
  port: 9000